### ISSUE TITLE
Run locally from a docker container on a dev machine/build server

### ISSUE THREAD

**Issue by gregoryca** [Surya742/Intellectify#1]
I've been able to create an docker image, and run a docker container using a docker-compose file.

How can Intellectify hook in to my local dev enviroment ? Do i need to give it access to my local file-system where my projects are saved so it can read the files, or is it better to run my dev-environment from within for example code server with Intellectify intergration ?

(both in a new image while combining them)

**Comment by Surya742** [comment]
Hi @gregoryca ,
You don't have to provide any access to your project folders/flies to intellectify, it's a plugin that will be attached to your vs-code environment hence it will automatically have access to all the files you opened in the vs-code window.

For that, you just need to run this extension in the development mode, open the `extension.js` file and press `F5`, this will run the local server for the intellectify, and a new window of the vs-code will get open where this extension will be by-default installed, now whatever folder/project you open in this new vs-code window will have access to the intellectify's feature.

As far as you will be able to shift this newly opened vs-code window from one image to another, you will be able to access intellectify's feature in different docker images.

Universal solution (Alternative): Just host this extension on the vs-code marketplace, and install it in your vs-code

Hope it cleared your issue!

**Comment by gregoryca** [comment]
Thank you very much for your quick answer. I think i made a mistake in my Dockerfile, since i'm using the server.js file, instead of the extension.js. (was too quick in creating the dockerfile)

Your second option would be a better universal solution to make it available to everyone.
Again thank you very much for your time, and the code offcoarse ! i can create fork with the docker image/compose file so you can maybe intergrate it.

**Comment by Surya742** [comment]
Sounds cool!!
