### ISSUE TITLE
Installing the plugin

### ISSUE THREAD

**Issue by Vampirebat** [Surya742/Intellectify#2]
once i have a project open this is my error 

I am error Error: Request failed with status code 401
	at createError (g:\Intellectify\node_modules\axios\lib\core\createError.js:16:15)
	at settle (g:\Intellectify\node_modules\axios\lib\core\settle.js:17:12)
	at IncomingMessage.handleStreamEnd (g:\Intellectify\node_modules\axios\lib\adapters\http.js:312:11)
	at IncomingMessage.emit (G:\Intellectify\lib\events.js:538:35)
	at endReadableNT (G:\Intellectify\lib\internal\streams\readable.js:1345:12)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21) {config: {…}, request: ClientRequest, response: {…}, isAxiosError: true, toJSON: ƒ, …}

arg1:
Error: Request failed with status code 401\n\tat createError (g:\\Intellectify\\node_modules\\axios\\lib\\core\\createError.js:16:15)\n\tat settle (g:\\Intellectify\\node_modules\\axios\\lib\\core\\settle.js:17:12)\n\tat IncomingMessage.handleStreamEnd (g:\\Intellectify\\node_modules\\axios\\lib\\adapters\\http.js:312:11)\n\tat IncomingMessage.emit (node:events:538:35)\n\tat endReadableNT (node:internal/streams/readable:1345:12)\n\tat process.processTicksAndRejections (node:internal/process/task_queues:83:21) {config: {…}, request: ClientRequest, response: {…}, isAxiosError: true, toJSON: ƒ, …}
f @ d:\Users\vamp\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:6

**Comment by Surya742** [comment]
Hi @Vampirebat ,
1. You are not just limited to java programs, you can work in any programming language or framework you want.
2.  Run "npm install", then "F5" to run the extension in the development mode.
3.  In this development mode vs-code window you can create or open any of your projects to use the intellectify with it.
4.  To use intellectify, Open your command pallet with ctr+shift+p, to see all the available features intellectify offers you.

Error 401 means unauthorized request, which means you didn't change the OpenAI API key, remember to change it with your own OpenAI API key (in .env file) by accessing the openai website (https://beta.openai.com/account/api-keys)

Hope it will solve your issue, ask me further if you still face any issues,
Thank you!

**Comment by Surya742** [comment]
Being inactive for a long time, I believe this issue must've been resolved using the latest go-around I've provided. 
Closing this issue now.
Thanks.
